library(tidyverse)
library(umap)
library(cluster)

setwd(r"(R:\Science\CetaceanOPPNoise\CetaceanOPPNoise_3\Other_PAM_Studies\2013-2021 Blue Whale Audible Call Library_ABabin\Call library testing\2025 amendments)")
attributes<-read.csv('Pooled_amplitude_weighted_attributes.csv')

custom.config<-umap.defaults
custom.config$min_dist<-0.0001
custom.config$random_state<-2204
dimension_reduction<-umap(attributes,config=custom.config)

three<-kmeans(dimension_reduction$layout,3)
write.csv(three$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\3.csv",row.names=FALSE)
four<-kmeans(dimension_reduction$layout,4)
write.csv(four$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\4.csv",row.names=FALSE)
five<-kmeans(dimension_reduction$layout,5)
write.csv(five$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\5.csv",row.names=FALSE)
six<-kmeans(dimension_reduction$layout,6)
write.csv(six$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\6.csv",row.names=FALSE)
seven<-kmeans(dimension_reduction$layout,7)
write.csv(seven$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\7.csv",row.names=FALSE)
eight<-kmeans(dimension_reduction$layout,8)
write.csv(eight$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\8.csv",row.names=FALSE)
nine<-kmeans(dimension_reduction$layout,9)
write.csv(nine$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\9.csv",row.names=FALSE)
ten<-kmeans(dimension_reduction$layout,10)
write.csv(ten$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\10.csv",row.names=FALSE)
eleven<-kmeans(dimension_reduction$layout,11)
write.csv(eleven$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\11.csv",row.names=FALSE)
twelve<-kmeans(dimension_reduction$layout,12)
write.csv(twelve$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\12.csv",row.names=FALSE)
thirteen<-kmeans(dimension_reduction$layout,13)
write.csv(thirteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\13.csv",row.names=FALSE)
fourteen<-kmeans(dimension_reduction$layout,14)
write.csv(fourteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\14.csv",row.names=FALSE)
fifteen<-kmeans(dimension_reduction$layout,15)
write.csv(fifteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\15.csv",row.names=FALSE)
sixteen<-kmeans(dimension_reduction$layout,16)
write.csv(sixteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\16.csv",row.names=FALSE)
seventeen<-kmeans(dimension_reduction$layout,17)
write.csv(seventeen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\17.csv",row.names=FALSE)
eighteen<-kmeans(dimension_reduction$layout,18)
write.csv(eighteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\18.csv",row.names=FALSE)
nineteen<-kmeans(dimension_reduction$layout,19)
write.csv(nineteen$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\19.csv",row.names=FALSE)
twenty<-kmeans(dimension_reduction$layout,20)
write.csv(twenty$cluster,"R:\\Science\\CetaceanOPPNoise\\CetaceanOPPNoise_3\\Other_PAM_Studies\\2013-2021 Blue Whale Audible Call Library_ABabin\\Call library testing\\2025 amendments\\UMAP and kmeans clusters\\20.csv",row.names=FALSE)
